### ISSUE TITLE
Add "Back to Top" Button

### ISSUE THREAD

**Issue by SyedaMahamFahim** [SyedaMahamFahim/syedamaham.dev#10]
**Issue Title:** Add "Back to Top" Button

**Description:**
We propose adding a "Back to Top" button to enhance user experience by allowing quick navigation to the top of long webpages.

**Why It's Important:**
- Improves user experience, especially on content-heavy pages.
- Enhances accessibility.
  
**Implementation:**
- Use JavaScript and CSS for smooth scrolling.
  
**Considerations:**
- Button position and styling.
- Configurability options.
  
**Discussion:**
Open for feedback and discussion.

**Comment by SyedaMahamFahim** [comment]
@Shubh8899, thank you for your interest! I genuinely appreciate your willingness to contribute.

**Issue:** Add a "Back to Top" Button

**Task Details:**
- I kindly request you to pull the main branch to get the latest code.
- Your efforts in implementing the "Back to Top" button, allowing users to smoothly return to the top of the page when needed, are highly appreciated.
- Your creative touch in styling this button is eagerly anticipated to ensure it complements the site's aesthetics.
- I have included installation instructions due to Sanity CMS; you may refer to it.

If any questions arise or if you would like further guidance, please do not hesitate to reach out. Your contributions truly make a difference. Thank you!

**Comment by Shubh8899** [comment]
I am not able to see screenshot for Installation(Sanity). @SyedaMahamFahim can you help?


<img width="1487" alt="Screenshot 2023-09-16 at 7 07 30 PM" src="https://github.com/SyedaMahamFahim/syedamaham.dev/assets/63413220/0bda6c81-ed9f-4478-a9e4-cd906dd53bcc">

**Comment by SyedaMahamFahim** [comment]
it was working fine in one browser, but when I checked it with another browser, it wasn't showing. However, I have now resolved the screenshot issue and also uploaded the [production.tar.gz](https://github.com/SyedaMahamFahim/syedamaham.dev/blob/main/production.tar.gz) folder to the main branch. Could you please pull it from the main branch before starting to work on it?
